// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VNV_NVDLA__SYMS_H_
#define VERILATED_VNV_NVDLA__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "VNV_nvdla.h"

// INCLUDE MODULE CLASSES
#include "VNV_nvdla___024root.h"
#include "VNV_nvdla_NV_NVDLA_partition_m.h"
#include "VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo.h"
#include "VNV_nvdla_NV_NVDLA_CDMA_dual_reg.h"
#include "VNV_nvdla_NV_NVDLA_CDMA_CVT_cell.h"
#include "VNV_nvdla_NV_NVDLA_SDP_REG_dual.h"
#include "VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo.h"
#include "VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo.h"
#include "VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo.h"
#include "VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo.h"
#include "VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo.h"
#include "VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt.h"
#include "VNV_nvdla_NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt.h"
#include "VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d.h"
#include "VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro.h"

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)VNV_nvdla__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    VNV_nvdla* const __Vm_modelp;
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    VNV_nvdla___024root            TOP;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_0;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_1;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_2;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_3;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_4;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_5;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_6;
    VNV_nvdla_NV_NVDLA_CDMA_CVT_cell TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_cvt__DOT__u_cell_7;
    VNV_nvdla_NV_NVDLA_CDMA_dual_reg TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_regfile__DOT__u_dual_reg_d0;
    VNV_nvdla_NV_NVDLA_CDMA_dual_reg TOP__NV_nvdla__DOT__u_partition_c__DOT__u_NV_NVDLA_cdma__DOT__u_regfile__DOT__u_dual_reg_d1;
    VNV_nvdla_NV_NVDLA_partition_m TOP__NV_nvdla__DOT__u_partition_ma;
    VNV_nvdla_NV_NVDLA_partition_m TOP__NV_nvdla__DOT__u_partition_mb;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro0_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro1_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro2_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro3_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro4_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro5_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro6_fifo;
    VNV_nvdla_NV_NVDLA_CDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro7_fifo;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo0;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo1;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo2;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo3;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo4;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo5;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo6;
    VNV_nvdla_NV_NVDLA_CDP_WDMA_dat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_cdp__DOT__u_wdma__DOT__u_dat0_fifo7;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo2;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo3;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo4;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo5;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_lat_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__lat_fifo6;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro0_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro0_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro1_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro1_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro2_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro2_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro3_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro3_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro4_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro4_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro5_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro5_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro6_fifo0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_EG_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_eg__DOT__ro6_fifo1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt2;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt3;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt4;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt5;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_READ_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_read__DOT__u_ig__DOT__u_bpt6;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_write__DOT__u_ig__DOT__u_bpt0;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_write__DOT__u_ig__DOT__u_bpt1;
    VNV_nvdla_NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_mcif__DOT__u_write__DOT__u_ig__DOT__u_bpt2;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_0;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_1;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_2;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_3;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_4;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_5;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_6;
    VNV_nvdla_NV_NVDLA_PDP_CORE_unit1d TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_core__DOT__u_cal1d__DOT__unit1d_7;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro0_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro1_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro2_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro3_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro4_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro5_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro6_fifo;
    VNV_nvdla_NV_NVDLA_PDP_RDMA_ro_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_rdma__DOT__u_eg__DOT__u_ro7_fifo;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo0;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo1;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo2;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo3;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo4;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo5;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo6;
    VNV_nvdla_NV_NVDLA_PDP_WDMA_DAT_fifo TOP__NV_nvdla__DOT__u_partition_o__DOT__u_NV_NVDLA_pdp__DOT__u_wdma__DOT__u_dat__DOT__u_dat0_fifo7;
    VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro TOP__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_brdma__DOT__u_eg__DOT__u_alu;
    VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro TOP__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_brdma__DOT__u_eg__DOT__u_mul;
    VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro TOP__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_nrdma__DOT__u_eg__DOT__u_alu;
    VNV_nvdla_NV_NVDLA_SDP_RDMA_EG_ro TOP__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_rdma__DOT__u_nrdma__DOT__u_eg__DOT__u_mul;
    VNV_nvdla_NV_NVDLA_SDP_REG_dual TOP__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_reg__DOT__u_dual_reg_d0;
    VNV_nvdla_NV_NVDLA_SDP_REG_dual TOP__NV_nvdla__DOT__u_partition_p__DOT__u_NV_NVDLA_sdp__DOT__u_reg__DOT__u_dual_reg_d1;

    // CONSTRUCTORS
    VNV_nvdla__Syms(VerilatedContext* contextp, const char* namep, VNV_nvdla* modelp);
    ~VNV_nvdla__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
